# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
stylua = "johnnymorganz/stylua@0.20.0"
darklua = "seaofvoices/darklua@0.13.1"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "kampfkarren/selene@0.27.1"
luau-lsp = "johnnymorganz/luau-lsp@1.32.4"
wally-patch-package = "Barocena/wally-patch-package@1.2.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
wally = "UpliftGames/wally@0.3.2"
lune = "lune-org/lune@0.8.8"
