[package]
name = "pepeeltoro41/ui-labs-vide"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
vide = "pepeeltoro41/modded-vide@0.0.5"
sift = "csqrl/sift@0.0.9"
janitor = "howmanysmall/janitor@1.17.0"
immut = "solarhorizon/immut@0.4.4"
charm = "littensy/charm@0.7.0"
ripple = "littensy/ripple@0.9.1"
collections = "jsdotlua/collections@1.2.7"
promise = "howmanysmall/typed-promise@4.0.3"
signal = "sleitnick/signal@2.0.1"
ui-labs = "pepeeltoro41/ui-labs@2.3.0"
