local Dark = {
	Background1 = Color3.fromRGB(18, 20, 24),
	Background2 = Color3.fromRGB(28, 30, 32),
	Background3 = Color3.fromRGB(34, 37, 44),
	Background4 = Color3.fromRGB(45, 49, 58),
	Background5 = Color3.fromRGB(91, 100, 99),

	PureColor = Color3.fromRGB(0, 0, 0),
	PureInverted = Color3.fromRGB(255, 255, 255),

	Text1 = Color3.fromRGB(255, 255, 255),
	Text2 = Color3.fromRGB(196, 196, 196),
	Text3 = Color3.fromRGB(156, 156, 156),
	TextInverted1 = Color3.fromRGB(15, 15, 15),
	TextInverted2 = Color3.fromRGB(41, 41, 41),
	TextInverted3 = Color3.fromRGB(63, 63, 63),

	TextActive1 = Color3.fromRGB(17, 10, 20),
	TextActive2 = Color3.fromRGB(37, 14, 30),
	TextActive3 = Color3.fromRGB(59, 36, 65),

	Emphasis = Color3.fromRGB(180, 133, 255),
	Emphasis2 = Color3.fromRGB(148, 99, 226),

	Border = Color3.fromHSV(0, 0, 0.5),

	Colors = {
		Red = Color3.fromRGB(199, 89, 89),
		Green = Color3.fromRGB(135, 255, 176),
		Blue = Color3.fromRGB(0, 0, 255),
	},

	Storybook = Color3.fromRGB(143, 240, 176),
	Folder = Color3.fromRGB(237, 166, 222),
	Story = Color3.fromRGB(120, 189, 232),
}

return Dark
