local Dark = {
	Background1 = Color3.fromRGB(18, 20, 24),
	Background2 = Color3.fromRGB(26, 28, 31),
	Background3 = Color3.fromRGB(31, 34, 41),
	Background4 = Color3.fromRGB(43, 47, 56),

	Text1 = Color3.fromRGB(255, 255, 255),
	Text2 = Color3.fromRGB(196, 196, 196),
	Text3 = Color3.fromRGB(156, 156, 156),
	TextInverted = Color3.fromRGB(17, 13, 16),
	Emphasis = Color3.fromRGB(180, 133, 255),

	Border = Color3.fromHSV(0, 0, 0.5),

	Colors = {
		Red = Color3.fromRGB(199, 89, 89),
		Green = Color3.fromRGB(135, 255, 176),
		Blue = Color3.fromRGB(0, 0, 255),
	},

	Storybook = Color3.fromRGB(143, 240, 176),
	Folder = Color3.fromRGB(237, 166, 222),
	Story = Color3.fromRGB(120, 189, 232),
}

return Dark
