local Dark = {
	background1 = Color3.fromRGB(18, 20, 24),
	background2 = Color3.fromRGB(28, 30, 32),
	background3 = Color3.fromRGB(34, 37, 44),
	background4 = Color3.fromRGB(45, 49, 58),
	background5 = Color3.fromRGB(91, 100, 99),

	pure = Color3.fromRGB(0, 0, 0),
	pure_inverted = Color3.fromRGB(255, 255, 255),

	text1 = Color3.fromRGB(255, 255, 255),
	text2 = Color3.fromRGB(196, 196, 196),
	text3 = Color3.fromRGB(156, 156, 156),

	text_inverted1 = Color3.fromRGB(15, 15, 15),
	text_inverted2 = Color3.fromRGB(41, 41, 41),
	text_inverted3 = Color3.fromRGB(63, 63, 63),

	text_active1 = Color3.fromRGB(17, 10, 20),
	text_active2 = Color3.fromRGB(37, 14, 30),
	text_active3 = Color3.fromRGB(59, 36, 65),

	emphasis = Color3.fromRGB(180, 133, 255),
	emphasis2 = Color3.fromRGB(148, 99, 226),

	border = Color3.fromHSV(0, 0, 0.5),

	colors = {
		red1 = Color3.fromRGB(199, 89, 89),
		green1 = Color3.fromRGB(135, 255, 176),
		blue1 = Color3.fromRGB(0, 0, 255),
	},

	storybook = Color3.fromRGB(143, 240, 176),
	folder = Color3.fromRGB(237, 166, 222),
	story = Color3.fromRGB(120, 189, 232),
}

return Dark
