export type Theme = {
	display_name: string,

	background1: Color3,
	background2: Color3,
	background3: Color3,
	background4: Color3,
	background5: Color3,

	pure: Color3,
	pure_inverted: Color3,

	text1: Color3,
	text2: Color3,
	text3: Color3,

	text_inverted1: Color3,
	text_inverted2: Color3,
	text_inverted3: Color3,

	text_active1: Color3,
	text_active2: Color3,
	text_active3: Color3,

	emphasis: Color3,
	emphasis2: Color3,

	border: Color3,

	red1: Color3,
	green1: Color3,
	blue1: Color3,

	storybook: Color3,
	folder: Color3,
	story: Color3,
}

return nil
